---
name: RSpec::SleepingKingStudios::Version::BUILD
parent_path: r-spec/sleeping-king-studios/version
slug: build
short_description: Build metadata.
value: '0'
data_path: r-spec/sleeping-king-studios/version/build
metadata:
  api: private
version: "*"
